import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sections/app-sidebar";
import Provider from "./provider";
import { TransactionsProvider } from "@/components/TransactionBar/TransactionsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <TransactionsProvider>
            <SidebarProvider>
              <AppSidebar />
              <main className="flex flex-col flex-1 min-h-screen">
                <SidebarTrigger />
                {children}
              </main>
            </SidebarProvider>
          </TransactionsProvider>
        </Provider>
      </body>
    </html>
  );
}
